version: 0.2

phases:
  build:
    commands:
      - echo "Packaging static HTML files (case-insensitive)..."
      - mkdir -p output
      - find . -iname "*.html" -exec cp {} output/ \;
      - find . -iname "*.css" -exec cp {} output/ \;
      - find . -iname "*.png" -exec cp {} output/ \;
      #If you have CSS/JS/images in 'assets' folder

artifacts:
  files:
    - '**/*'
  base-directory: output
  name: static-website.zip
  post_build:
    commands:
        - file=$(find output -iname "webpage.html")
        - if [ -n "$file" ]; then mv "$file" output/index.html; fi

