version: 0.2

phases:
  build:
    commands:
      - echo "Packaging static HTML files..."
      - mkdir -p output
      - shopt -s nocaseglob
      - cp -r *.html output/
      - cp -r *.css output/
      - cp -r *.png output/
      - shopt -u nocaseglob
      # If you have CSS/JS/images in 'assets' folder

artifacts:
  files:
    - '**/*'
  base-directory: output
  name: static-website.zip
  post_build:
    commands:
        - mv output/WEBPAGE.HTML output/index.html

