version: 0.2
env:
  variables:
    HOST_BUCKET: staticlogsbucketkv
phases:
  build:
    commands:
      - echo "Packaging static HTML files (case-insensitive)..."
      - mkdir -p output
      - find . -iname "*.html" -exec cp {} output/ \;
      - find . -iname "*.css" -exec cp {} output/ \;
      - find . -iname "*.js" -exec cp {} output/ \;
      #- find . -iname "*.png" -exec cp {} output/ \;
      - "[ -d assets ] && cp -r assets/ output/ || echo 'No assets folder found'"
  post_build:
    commands:
      - file=$(find output -iname "webpage.html")
      - if [ -n "$file" ] && [ ! -f output/index.html ]; then mv "$file" output/index.html; fi
      - echo "Backing up current S3 contents..."
      - aws s3 sync s3://$HOST_BUCKET s3://$HOST_BUCKET-backup/$(date +%Y%m%d-%H%M%S)
      - echo "Syncing new content with --delete..."
      - aws s3 sync output/ s3://$HOST_BUCKET --delete
      - echo "Sync completed at $(date)" >> sync.log
      - aws s3 cp sync.log s3://$HOST_BUCKET/logs/sync-$(date +%Y%m%d-%H%M%S).log
artifacts:
  files:
    - '**/*'
  base-directory: output
  name: static-website.zip
