version: 0.2

phases:
  build:
    commands:
      - echo "Packaging static HTML files..."
      - mkdir -p output
      - cp -r *.html output/
      - cp -r *.css output/
      - cp -r *.png output/
      # If you have CSS/JS/images in 'assets' folder

artifacts:
  files:
    - '**/*'
  base-directory: output
  name: static-website.zip
